In [3]:
import numpy as np
import math
from itertools import combinations
from numpy import linalg as la
math.isclose(0.1 + 0.2, 0.3)


True

In [14]:
def bmatrix(a):
    """Returns a LaTeX bmatrix

    :a: numpy array
    :returns: LaTeX bmatrix as a string
    """
    if len(a.shape) > 2:
        raise ValueError('bmatrix can at most display two dimensions')
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{bmatrix}']
    rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
    rv += [r'\end{bmatrix}']
    return '\n'.join(rv)


In [104]:
import numpy as np
from numpy import linalg as la
from IPython.display import display_markdown, Markdown
import sympy as sp


def basic_solutions(A, b):
    m, n = A.shape
    print("Number of combinations: %d" % math.comb(n, m))
    combN = list(combinations(range(n), n - m))
    for k, comb in enumerate(combinations(range(n), m)):
        x = np.zeros(n)
        try:
            B_inv = la.inv(A[:, list(comb)])
            x_b = B_inv@b  # x_n are zeros
            x[list(comb)] = x_b
            u = sp.Matrix([f"x_{i+1}" for i in comb])
            v = sp.Matrix([f"x_{i+1}" for i in combN[10 - k -1]])
            # print(f"x{[i + 1 for i in comb]} = {bmatrix(x)}")
            display_markdown(Markdown(
                f"$$B={bmatrix(A[:, list(comb)])},\quad \mathbf{{x}}_B = {sp.latex(u)}=B^{{-1}}\mathbf{{b}}={bmatrix(B_inv)}{bmatrix(b.reshape(-1, 1))} = {bmatrix(x_b.reshape(-1, 1))}, \quad \mathbf{{x}}={bmatrix(x.reshape(-1, 1))}$$"))
            display_markdown(Markdown(f"$$\mathbf{{x}}_N={sp.latex(v)}={bmatrix(np.zeros((n- m, 1), dtype=int))}$$"))
        except Exception as ex:
            print("Column index =", comb, ex)
            continue


In [113]:
A = np.array([[1, 2, 2, 1, 0],
              [2, 1, 2, 0, 1]])

display_markdown(Markdown(f"$$[A|I_2]=[a_1, a_2, a_3, a_4, a_5]={bmatrix(A)}$$"))

$$[A|I_2]=[a_1, a_2, a_3, a_4, a_5]=\begin{bmatrix}
  1 & 2 & 2 & 1 & 0\\
  2 & 1 & 2 & 0 & 1\\
\end{bmatrix}$$

In [105]:
A = np.array([[1, 2, 2, 1, 0],
              [2, 1, 2, 0, 1]])

b = np.array([4, 3])

basic_solutions(A, b)


Number of combinations: 10


$$B=\begin{bmatrix}
  1 & 2\\
  2 & 1\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{1}\\x_{2}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  -0.33333333 & 0.66666667\\
  0.66666667 & -0.33333333\\
\end{bmatrix}\begin{bmatrix}
  4\\
  3\\
\end{bmatrix} = \begin{bmatrix}
  0.66666667\\
  1.66666667\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  0.66666667\\
  1.66666667\\
  0.\\
  0.\\
  0.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{3}\\x_{4}\\x_{5}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  1 & 2\\
  2 & 2\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{1}\\x_{3}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  -1. & 1.\\
  1. & -0.5\\
\end{bmatrix}\begin{bmatrix}
  4\\
  3\\
\end{bmatrix} = \begin{bmatrix}
  -1.\\
  2.5\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  -1.\\
  0.\\
  2.5\\
  0.\\
  0.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{2}\\x_{4}\\x_{5}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  1 & 1\\
  2 & 0\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{1}\\x_{4}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  0. & 0.5\\
  1. & -0.5\\
\end{bmatrix}\begin{bmatrix}
  4\\
  3\\
\end{bmatrix} = \begin{bmatrix}
  1.5\\
  2.5\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  1.5\\
  0.\\
  0.\\
  2.5\\
  0.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{2}\\x_{3}\\x_{5}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  1 & 0\\
  2 & 1\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{1}\\x_{5}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  1. & 0.\\
  -2. & 1.\\
\end{bmatrix}\begin{bmatrix}
  4\\
  3\\
\end{bmatrix} = \begin{bmatrix}
  4.\\
  -5.\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  4.\\
  0.\\
  0.\\
  0.\\
  -5.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{2}\\x_{3}\\x_{4}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  2 & 2\\
  1 & 2\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{2}\\x_{3}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  1. & -1.\\
  -0.5 & 1.\\
\end{bmatrix}\begin{bmatrix}
  4\\
  3\\
\end{bmatrix} = \begin{bmatrix}
  1.\\
  1.\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  0.\\
  1.\\
  1.\\
  0.\\
  0.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{1}\\x_{4}\\x_{5}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  2 & 1\\
  1 & 0\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{2}\\x_{4}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  0. & 1.\\
  1. & -2.\\
\end{bmatrix}\begin{bmatrix}
  4\\
  3\\
\end{bmatrix} = \begin{bmatrix}
  3.\\
  -2.\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  0.\\
  3.\\
  0.\\
  -2.\\
  0.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{1}\\x_{3}\\x_{5}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  2 & 0\\
  1 & 1\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{2}\\x_{5}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  0.5 & 0.\\
  -0.5 & 1.\\
\end{bmatrix}\begin{bmatrix}
  4\\
  3\\
\end{bmatrix} = \begin{bmatrix}
  2.\\
  1.\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  0.\\
  2.\\
  0.\\
  0.\\
  1.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{1}\\x_{3}\\x_{4}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  2 & 1\\
  2 & 0\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{3}\\x_{4}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  0. & 0.5\\
  1. & -1.\\
\end{bmatrix}\begin{bmatrix}
  4\\
  3\\
\end{bmatrix} = \begin{bmatrix}
  1.5\\
  1.\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  0.\\
  0.\\
  1.5\\
  1.\\
  0.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{1}\\x_{2}\\x_{5}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  2 & 0\\
  2 & 1\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{3}\\x_{5}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  0.5 & 0.\\
  -1. & 1.\\
\end{bmatrix}\begin{bmatrix}
  4\\
  3\\
\end{bmatrix} = \begin{bmatrix}
  2.\\
  -1.\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  0.\\
  0.\\
  2.\\
  0.\\
  -1.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{1}\\x_{2}\\x_{4}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  1 & 0\\
  0 & 1\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{4}\\x_{5}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  1. & 0.\\
  0. & 1.\\
\end{bmatrix}\begin{bmatrix}
  4\\
  3\\
\end{bmatrix} = \begin{bmatrix}
  4.\\
  3.\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  0.\\
  0.\\
  0.\\
  4.\\
  3.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{1}\\x_{2}\\x_{3}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
  0\\
\end{bmatrix}$$

In [114]:
A = np.array([[9, 8, 1, 0, 0],
              [-1, 7, 0, 1, 0],
              [5, 0, 0, 0, 1.]])

b = np.array([1, 2., 3])

basic_solutions(A, b)


Number of combinations: 10


$$B=\begin{bmatrix}
  9. & 8. & 1.\\
  -1. & 7. & 0.\\
  5. & 0. & 0.\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{1}\\x_{2}\\x_{3}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  0. & 0. & 0.2\\
  0. & 0.14285714 & 0.02857143\\
  1. & -1.14285714 & -2.02857143\\
\end{bmatrix}\begin{bmatrix}
  1.\\
  2.\\
  3.\\
\end{bmatrix} = \begin{bmatrix}
  0.6\\
  0.37142857\\
  -7.37142857\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  0.6\\
  0.37142857\\
  -7.37142857\\
  0.\\
  0.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{4}\\x_{5}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  9. & 8. & 0.\\
  -1. & 7. & 1.\\
  5. & 0. & 0.\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{1}\\x_{2}\\x_{4}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  0. & 0. & 0.2\\
  0.125 & 0. & -0.225\\
  -0.875 & 1. & 1.775\\
\end{bmatrix}\begin{bmatrix}
  1.\\
  2.\\
  3.\\
\end{bmatrix} = \begin{bmatrix}
  0.6\\
  -0.55\\
  6.45\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  0.6\\
  -0.55\\
  0.\\
  6.45\\
  0.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{3}\\x_{5}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  9. & 8. & 0.\\
  -1. & 7. & 0.\\
  5. & 0. & 1.\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{1}\\x_{2}\\x_{5}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  0.09859155 & -0.11267606 & 0.\\
  0.01408451 & 0.12676056 & 0.\\
  -0.49295775 & 0.56338028 & 1.\\
\end{bmatrix}\begin{bmatrix}
  1.\\
  2.\\
  3.\\
\end{bmatrix} = \begin{bmatrix}
  -0.12676056\\
  0.26760563\\
  3.63380282\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  -0.12676056\\
  0.26760563\\
  0.\\
  0.\\
  3.63380282\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{3}\\x_{4}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  9. & 1. & 0.\\
  -1. & 0. & 1.\\
  5. & 0. & 0.\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{1}\\x_{3}\\x_{4}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  0.00000000e+00 & 0.00000000e+00 & 2.00000000e-01\\
  1.00000000e+00 & -0.00000000e+00 & -1.80000000e+00\\
  1.38777878e-17 & 1.00000000e+00 & 2.00000000e-01\\
\end{bmatrix}\begin{bmatrix}
  1.\\
  2.\\
  3.\\
\end{bmatrix} = \begin{bmatrix}
  0.6\\
  -4.4\\
  2.6\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  0.6\\
  0.\\
  -4.4\\
  2.6\\
  0.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{2}\\x_{5}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  9. & 1. & 0.\\
  -1. & 0. & 0.\\
  5. & 0. & 1.\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{1}\\x_{3}\\x_{5}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  -2.46716228e-17 & -1.00000000e+00 & 0.00000000e+00\\
  1.00000000e+00 & 9.00000000e+00 & -0.00000000e+00\\
  6.93889390e-17 & 5.00000000e+00 & 1.00000000e+00\\
\end{bmatrix}\begin{bmatrix}
  1.\\
  2.\\
  3.\\
\end{bmatrix} = \begin{bmatrix}
  -2.\\
  19.\\
  13.\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  -2.\\
  0.\\
  19.\\
  0.\\
  13.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{2}\\x_{4}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  9. & 0. & 0.\\
  -1. & 1. & 0.\\
  5. & 0. & 1.\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{1}\\x_{4}\\x_{5}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  0.11111111 & 0. & 0.\\
  0.11111111 & 1. & 0.\\
  -0.55555556 & 0. & 1.\\
\end{bmatrix}\begin{bmatrix}
  1.\\
  2.\\
  3.\\
\end{bmatrix} = \begin{bmatrix}
  0.11111111\\
  2.11111111\\
  2.44444444\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  0.11111111\\
  0.\\
  0.\\
  2.11111111\\
  2.44444444\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{2}\\x_{3}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
\end{bmatrix}$$

Column index = (1, 2, 3) Singular matrix


$$B=\begin{bmatrix}
  8. & 1. & 0.\\
  7. & 0. & 0.\\
  0. & 0. & 1.\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{2}\\x_{3}\\x_{5}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  0. & 0.14285714 & 0.\\
  1. & -1.14285714 & -0.\\
  0. & 0. & 1.\\
\end{bmatrix}\begin{bmatrix}
  1.\\
  2.\\
  3.\\
\end{bmatrix} = \begin{bmatrix}
  0.28571429\\
  -1.28571429\\
  3.\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  0.\\
  0.28571429\\
  -1.28571429\\
  0.\\
  3.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{1}\\x_{4}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  8. & 0. & 0.\\
  7. & 1. & 0.\\
  0. & 0. & 1.\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{2}\\x_{4}\\x_{5}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  0.125 & 0. & 0.\\
  -0.875 & 1. & 0.\\
  0. & 0. & 1.\\
\end{bmatrix}\begin{bmatrix}
  1.\\
  2.\\
  3.\\
\end{bmatrix} = \begin{bmatrix}
  0.125\\
  1.125\\
  3.\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  0.\\
  0.125\\
  0.\\
  1.125\\
  3.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{1}\\x_{3}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
\end{bmatrix}$$

$$B=\begin{bmatrix}
  1. & 0. & 0.\\
  0. & 1. & 0.\\
  0. & 0. & 1.\\
\end{bmatrix},\quad \mathbf{x}_B = \left[\begin{matrix}x_{3}\\x_{4}\\x_{5}\end{matrix}\right]=B^{-1}\mathbf{b}=\begin{bmatrix}
  1. & 0. & 0.\\
  0. & 1. & 0.\\
  0. & 0. & 1.\\
\end{bmatrix}\begin{bmatrix}
  1.\\
  2.\\
  3.\\
\end{bmatrix} = \begin{bmatrix}
  1.\\
  2.\\
  3.\\
\end{bmatrix}, \quad \mathbf{x}=\begin{bmatrix}
  0.\\
  0.\\
  1.\\
  2.\\
  3.\\
\end{bmatrix}$$

$$\mathbf{x}_N=\left[\begin{matrix}x_{1}\\x_{2}\end{matrix}\right]=\begin{bmatrix}
  0\\
  0\\
\end{bmatrix}$$

In [128]:
comb

[(0, 1, 2),
 (0, 1, 3),
 (0, 1, 4),
 (0, 1, 5),
 (0, 1, 6),
 (0, 1, 7),
 (0, 1, 8),
 (0, 1, 9),
 (0, 2, 3),
 (0, 2, 4),
 (0, 2, 5),
 (0, 2, 6),
 (0, 2, 7),
 (0, 2, 8),
 (0, 2, 9),
 (0, 3, 4),
 (0, 3, 5),
 (0, 3, 6),
 (0, 3, 7),
 (0, 3, 8),
 (0, 3, 9),
 (0, 4, 5),
 (0, 4, 6),
 (0, 4, 7),
 (0, 4, 8),
 (0, 4, 9),
 (0, 5, 6),
 (0, 5, 7),
 (0, 5, 8),
 (0, 5, 9),
 (0, 6, 7),
 (0, 6, 8),
 (0, 6, 9),
 (0, 7, 8),
 (0, 7, 9),
 (0, 8, 9),
 (1, 2, 3),
 (1, 2, 4),
 (1, 2, 5),
 (1, 2, 6),
 (1, 2, 7),
 (1, 2, 8),
 (1, 2, 9),
 (1, 3, 4),
 (1, 3, 5),
 (1, 3, 6),
 (1, 3, 7),
 (1, 3, 8),
 (1, 3, 9),
 (1, 4, 5),
 (1, 4, 6),
 (1, 4, 7),
 (1, 4, 8),
 (1, 4, 9),
 (1, 5, 6),
 (1, 5, 7),
 (1, 5, 8),
 (1, 5, 9),
 (1, 6, 7),
 (1, 6, 8),
 (1, 6, 9),
 (1, 7, 8),
 (1, 7, 9),
 (1, 8, 9),
 (2, 3, 4),
 (2, 3, 5),
 (2, 3, 6),
 (2, 3, 7),
 (2, 3, 8),
 (2, 3, 9),
 (2, 4, 5),
 (2, 4, 6),
 (2, 4, 7),
 (2, 4, 8),
 (2, 4, 9),
 (2, 5, 6),
 (2, 5, 7),
 (2, 5, 8),
 (2, 5, 9),
 (2, 6, 7),
 (2, 6, 8),
 (2, 6, 9),
 (2, 7, 8),
 (2,

In [135]:
len(comb)

10

In [152]:
A = sp.Matrix([["a", "b", 1, 0, 0],
              [-1, "c", 0, 1, 0],
              ["d", 0, 0, 0, 1.]])

b = sp.Matrix([1, 2, 3])
comb = list(combinations(range(5), 3))

for u in range(10):
    try:
        B = A.col(comb[u])
        print(comb[u])
        display((B.inv()*b))
    except Exception as e:
        print(e)


(0, 1, 2)


Matrix([
[                           3/d],
[                 2/c + 3/(c*d)],
[-3*a/d - 2*b/c - 3*b/(c*d) + 1]])

(0, 1, 3)


Matrix([
[                        3/d],
[           -3*a/(b*d) + 1/b],
[3*a*c/(b*d) + 2 + 3/d - c/b]])

(0, 1, 4)


Matrix([
[                               -2*b/(a*c + b) + c/(a*c + b)],
[                             -2*a/(-a*c - b) - 1/(-a*c - b)],
[2.0*b*d/(1.0*a*c + 1.0*b) - 1.0*c*d/(1.0*a*c + 1.0*b) + 3.0]])

(0, 2, 3)


Matrix([
[       3/d],
[-3*a/d + 1],
[   2 + 3/d]])

(0, 2, 4)


Matrix([
[         -2],
[    2*a + 1],
[2.0*d + 3.0]])

(0, 3, 4)


Matrix([
[          1/a],
[      2 + 1/a],
[3.0 - 1.0*d/a]])

(1, 2, 3)
Matrix det == 0; not invertible.
(1, 2, 4)


Matrix([
[       2/c],
[-2*b/c + 1],
[       3.0]])

(1, 3, 4)


Matrix([
[    1/b],
[2 - c/b],
[    3.0]])

(2, 3, 4)


Matrix([
[  1],
[  2],
[3.0]])

In [87]:
A = np.array([[1, 1, 1, 0, 0],
              [0, 1, 0, 1, 0], 
              [1, 2, 0, 0, 1]])

b = np.array([6, 3, 9])

basic_solutions(A, b)

Number of combinations: 10
x = [3. 3. 0. 0. 0.]
x = [3. 3. 0. 0. 0.]
x = [3. 3. 0. 0. 0.]
x = [ 9.  0. -3.  3.  0.]
Column index = (0, 2, 4) Singular matrix
x = [6. 0. 0. 3. 3.]
x = [ 0.   4.5  1.5 -1.5  0. ]
x = [0. 3. 3. 0. 3.]
x = [ 0.  6.  0. -3. -3.]
x = [0. 0. 6. 3. 9.]


In [10]:
def simplex(A, b, c):
    tableau = np.r_[c.reshape(1, -1), A]
    tableau = np.c_[tableau, np.insert(b, 0, 0)]

    basic_var = np.where(tableau[0, :-1] == 0)[0]
    while not (tableau[0] <= 0).all():
        c_max = np.argmax(tableau[0])
        # ratio minimum
        r_min = np.argmin(tableau[1:, -1]/tableau[1:, c_max]) + 1
        # escale row min to 1.0
        tableau[r_min] = tableau[r_min]/tableau[r_min, c_max]
        # pivot
        for i in range(len(A)):
            if i != r_min:
                tableau[i] = tableau[i] - tableau[i, c_max]*tableau[r_min, :]

        # swap row with col
        basic_var[r_min - 1] = c_max
        print(tableau)
    return tableau, basic_var


Ejemplo 1

In [5]:
c = np.array([4, 5, 0, 0, 0.])

A = np.array([[2, 1, 1, 0, 0],
              [1, 0, 0, 1, 0],
              [0, 1, 0, 0, 1.]])

b = np.array([9, 4, 3.])

tableau, basic_var = simplex(A, b, c)
print("Simplex Table:\n", tableau)

x_opt = np.zeros(5)
x_opt[basic_var] = tableau[1:, -1]
print(f"x óptimo = {x_opt}, c óptimo = {-tableau[0, -1]}")


Simplex Table:
 [[  0.    0.   -2.    0.   -3.  -27. ]
 [  1.    0.    0.5   0.   -0.5   3. ]
 [  0.    0.   -0.5   1.    0.5   1. ]
 [  0.    1.    0.    0.    1.    3. ]]
x óptimo = [3. 3. 0. 1. 0.], c óptimo = 27.0


C:\Users\jbard\AppData\Local\Temp\ipykernel_11792\339122210.py:9: RuntimeWarning: divide by zero encountered in true_divide
  r_min = np.argmin(tableau[1:, -1]/tableau[1:, c_max]) + 1


Ejemplo 2

In [6]:
c = np.array([-1, 1, 0, 0, 0.])

A = np.array([[-2, 6, 1, 0, 0],
              [2, 4, 0, 1, 0.],
              [1, 0, 0, 0, 1.]])

b = np.array([0, 10, 4.])

tableau, basic_var = simplex(A, b, c)
print("Simplex Table:\n", tableau)

x_opt = np.zeros(5)
x_opt[basic_var] = tableau[1:, -1]
print(f"x óptimo = {x_opt}, c óptimo = {-tableau[0, -1]}")


Simplex Table:
 [[-0.66666667  0.         -0.16666667  0.          0.          0.        ]
 [-0.33333333  1.          0.16666667  0.          0.          0.        ]
 [ 3.33333333  0.         -0.66666667  1.          0.         10.        ]
 [ 1.          0.          0.          0.          1.          4.        ]]
x óptimo = [ 0.  0.  0. 10.  4.], c óptimo = -0.0


C:\Users\jbard\AppData\Local\Temp\ipykernel_11792\339122210.py:9: RuntimeWarning: divide by zero encountered in true_divide
  r_min = np.argmin(tableau[1:, -1]/tableau[1:, c_max]) + 1


In [11]:
c = np.array([1, 2, 0, 0, 0.])

A = np.array([[1, 3, 1, 0, 0],
              [3, 3, 0, 1, 0.],
              [0, 3, 0, 0, 1.]])

b = np.array([3, 7, 1.])

tableau, basic_var = simplex(A, b, c)
print("Simplex Table:\n", tableau)

x_opt = np.zeros(5)
x_opt[basic_var] = tableau[1:, -1]
print(f"x óptimo = {x_opt}, c óptimo = {-tableau[0, -1]}")


[[ 1.          0.          0.          0.         -0.66666667 -0.66666667]
 [ 1.          0.          1.          0.         -1.          2.        ]
 [ 3.          0.          0.          1.         -1.          6.        ]
 [ 0.          1.          0.          0.          0.33333333  0.33333333]]
[[ 0.          0.         -1.          0.          0.33333333 -2.66666667]
 [ 1.          0.          1.          0.         -1.          2.        ]
 [ 0.          0.         -3.          1.          2.          0.        ]
 [ 0.          1.          0.          0.          0.33333333  0.33333333]]
[[ 0.33333333  0.         -0.66666667  0.          0.         -2.        ]
 [-1.         -0.         -1.         -0.          1.         -2.        ]
 [ 2.          0.         -1.          1.          0.          4.        ]
 [ 0.          1.          0.          0.          0.33333333  0.33333333]]
[[ 0.          0.         -1.          0.          0.33333333 -2.66666667]
 [ 1.          0.     

C:\Users\jbard\AppData\Local\Temp\ipykernel_11792\497010495.py:9: RuntimeWarning: divide by zero encountered in true_divide
  r_min = np.argmin(tableau[1:, -1]/tableau[1:, c_max]) + 1


[[ 0.33333333  0.         -0.66666667  0.          0.         -2.        ]
 [-1.         -0.         -1.         -0.          1.         -2.        ]
 [ 2.          0.         -1.          1.          0.          4.        ]
 [ 0.          1.          0.          0.          0.33333333  0.33333333]]
[[ 0.          0.         -1.          0.          0.33333333 -2.66666667]
 [ 1.          0.          1.          0.         -1.          2.        ]
 [ 0.          0.         -3.          1.          2.          0.        ]
 [ 0.          1.          0.          0.          0.33333333  0.33333333]]
[[ 0.33333333  0.         -0.66666667  0.          0.         -2.        ]
 [-1.         -0.         -1.         -0.          1.         -2.        ]
 [ 2.          0.         -1.          1.          0.          4.        ]
 [ 0.          1.          0.          0.          0.33333333  0.33333333]]
[[ 0.          0.         -1.          0.          0.33333333 -2.66666667]
 [ 1.          0.     

KeyboardInterrupt: 

In [13]:
a = np.array([1, 2, 3., 3, 3])
np.argmax(a)


2