Import libraries

In [1]:
import numpy as np
import sympy as sp
from util import  build_tableau, optimal_solution, correct_all_tableau
from util2 import check_tableau, tableau2standard
from simplex_algorithm import simplex, big_M, two_phases
np.set_printoptions(suppress=True, linewidth=np.nan)


### Book: Linear and Integer Optimization


#### Dovetail Model 
$$\begin{align*}
\max  3 x_{1}&+2 x_{2}& \\
\text { s.t. } \quad x_{1}&+x_{2}& \leq 9 \\
3 x_{1}&+x_{2}& \leq 18 \\
x_{1}&{} {}& \leq 7 \\
{}& \quad x_{2} & \leq 6 \\
x_{1}&, x_{2} \geq 0
\end{align*}$$

In [8]:
A = [[1, 1, 1, 0, 0, 0],
     [3, 1, 0, 1, 0, 0],
     [1, 0, 0, 0, 1, 0],
     [0, 1, 0, 0, 0, 1.0]]

b = [9, 18, 7, 6.]

c = [3, 2, 0, 0, 0, 0.]

basic_var = [2, 3, 4, 5]

tableau = build_tableau(A, b, c)
simplex(tableau, basic_var)
optimal_solution(tableau, basic_var)


vertex = [0. 0.], x_B = [3, 4, 5, 6]
[[ 3.  2.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  9.]
 [ 3.  1.  0.  1.  0.  0. 18.]
 [ 1.  0.  0.  0.  1.  0.  7.]
 [ 0.  1.  0.  0.  0.  1.  6.]]
vertex = [6. 0.], x_B = [3, 1, 5, 6]
[[  0.           1.           0.          -1.           0.           0.         -18.        ]
 [  0.           0.66666667   1.          -0.33333333   0.           0.           3.        ]
 [  1.           0.33333333   0.           0.33333333   0.           0.           6.        ]
 [  0.          -0.33333333   0.          -0.33333333   1.           0.           1.        ]
 [  0.           1.           0.           0.           0.           1.           6.        ]]
vertex = [4.5 4.5], x_B = [2, 1, 5, 6]
[[  0.    0.   -1.5  -0.5   0.    0.  -22.5]
 [  0.    1.    1.5  -0.5   0.    0.    4.5]
 [  1.    0.   -0.5   0.5   0.    0.    4.5]
 [  0.    0.    0.5  -0.5   1.    0.    2.5]
 [  0.    0.   -1.5   0.5   0.    1.    1.5]]
Optimal solution: x_opt = [4.5 4.5

**Two-Phases**: Dovetail Model modified: Constraint added $x_1 + x_2 \ge 5$

In [9]:
tableau = np.array([[0, 0, 0, 0, 0, 0, 0, -1, 0],
                    [1, 1, 1, 0, 0, 0, 0, 0, 9.],
                    [3, 1, 0, 1, 0, 0, 0, 0, 18],
                    [1, 0, 0, 0, 1, 0, 0, 0, 7.],
                    [0, 1, 0, 0, 0, 1, 0, 0, 6.],
                    [1, 1, 0, 0, 0, 0, -1, 1, 5]])

c = [3, 2, 0, 0, 0, 0, 0.]

basic_var = [2, 3, 4, 5, 7]
artificial_var = [7]

tableau = two_phases(tableau, c, basic_var, artificial_var)
optimal_solution(tableau, basic_var)


x_B = [3, 4, 5, 6, 8]
[[ 0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 1.  1.  1.  0.  0.  0.  0.  0.  9.]
 [ 3.  1.  0.  1.  0.  0.  0.  0. 18.]
 [ 1.  0.  0.  0.  1.  0.  0.  0.  7.]
 [ 0.  1.  0.  0.  0.  1.  0.  0.  6.]
 [ 1.  1.  0.  0.  0.  0. -1.  1.  5.]]
Cost corrected
x_B = [3, 4, 5, 6, 8]
[[ 1.  1.  0.  0.  0.  0. -1.  0.  5.]
 [ 1.  1.  1.  0.  0.  0.  0.  0.  9.]
 [ 3.  1.  0.  1.  0.  0.  0.  0. 18.]
 [ 1.  0.  0.  0.  1.  0.  0.  0.  7.]
 [ 0.  1.  0.  0.  0.  1.  0.  0.  6.]
 [ 1.  1.  0.  0.  0.  0. -1.  1.  5.]]
Start phase One
x_B = [3, 4, 5, 6, 1]
[[ 0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  1.  0.  0.  0.  1. -1.  4.]
 [ 0. -2.  0.  1.  0.  0.  3. -3.  3.]
 [ 0. -1.  0.  0.  1.  0.  1. -1.  2.]
 [ 0.  1.  0.  0.  0.  1.  0.  0.  6.]
 [ 1.  1.  0.  0.  0.  0. -1.  1.  5.]]
Delete artificial variables and create a new tableau [7]
Start phase two, put original cost
x_B = [3, 4, 5, 6, 1]
[[ 3.  2.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  1.  4.]
 [ 0. -2.  0. 

**BIG-M**:  Ejemplo visto el ciclo pasado Lineal 6 

In [10]:
M = 10
A = [[2, -1, -1, 0, 0, 1, 0],
     [-1, 2, 0, -1, 0, 0, 1],
     [1, 1., 0., 0, 1, 0, 0.]]

b = [4, 2, 12.]

c = [2, 1, 0, 0, 0, -M, -M]

basic_var = [5, 6, 4]
artificial_var = [5, 6]

tableau = build_tableau(A, b, c)
tableau = big_M(tableau, basic_var, artificial_var)
optimal_solution(tableau, basic_var)


x_B = [6, 7, 5]
[[  2.   1.   0.   0.   0. -10. -10.   0.]
 [  2.  -1.  -1.   0.   0.   1.   0.   4.]
 [ -1.   2.   0.  -1.   0.   0.   1.   2.]
 [  1.   1.   0.   0.   1.   0.   0.  12.]]
Cost corrected
vertex = [0. 0. 0. 0.], x_B = [6, 7, 5]
[[ 12.  11. -10. -10.   0.   0.   0.  60.]
 [  2.  -1.  -1.   0.   0.   1.   0.   4.]
 [ -1.   2.   0.  -1.   0.   0.   1.   2.]
 [  1.   1.   0.   0.   1.   0.   0.  12.]]
vertex = [2. 0. 0. 0.], x_B = [1, 7, 5]
[[  0.   17.   -4.  -10.    0.   -6.    0.   36. ]
 [  1.   -0.5  -0.5   0.    0.    0.5   0.    2. ]
 [  0.    1.5  -0.5  -1.    0.    0.5   1.    4. ]
 [  0.    1.5   0.5   0.    1.   -0.5   0.   10. ]]
vertex = [3.33333333 2.66666667 0.         0.        ], x_B = [1, 2, 5]
[[  0.           0.           1.66666667   1.33333333   0.         -11.66666667 -11.33333333  -9.33333333]
 [  1.           0.          -0.66666667  -0.33333333   0.           0.66666667   0.33333333   3.33333333]
 [  0.           1.          -0.33333333  -0.6666666

#### Equality constraints
Example 3.8.1. Consideer the following LO-model 
\begin{align*}
\max  40 x_{1}& + 100 x_{2}  + 150 x_{3}  \\
\text { s.t. }\quad x_{1} & + 2 x_{2}  +2 x_{3} =3 \\
 30 x_{1}& + 10 x_{2}  + 20 x_{3} =75 \\
 x_{1}&, x_{2}, x_{3} \geq 0
\end{align*}

Method 1: Big-M

Add artificial variable $u_1$ and $u_2$, the simplex algorithm will put highest priority on making the value of the factor $Mu_i$ as small as possible, thereby setting the value of $u_i$ equal to zero to maintain equality.

In [11]:
M = 100
A = [[1.0, 2, 2., 1, 0],
     [30, 10, 20, 0, 1]]

b = [3, 75.]
c = [40, 100, 150., -M, -M]

basic_var = [3, 4]

tableau = build_tableau(A, b, c)
tableau = big_M(tableau, basic_var, [])
optimal_solution(tableau, basic_var)


x_B = [4, 5]
[[  40.  100.  150. -100. -100.    0.]
 [   1.    2.    2.    1.    0.    3.]
 [  30.   10.   20.    0.    1.   75.]]
Cost corrected
vertex = [0. 0. 0.], x_B = [4, 5]
[[3140. 1300. 2350.    0.    0. 7800.]
 [   1.    2.    2.    1.    0.    3.]
 [  30.   10.   20.    0.    1.   75.]]
vertex = [2.5 0.  0. ], x_B = [4, 1]
[[   0.          253.33333333  256.66666667    0.         -104.66666667  -50.        ]
 [   0.            1.66666667    1.33333333    1.           -0.03333333    0.5       ]
 [   1.            0.33333333    0.66666667    0.            0.03333333    2.5       ]]
vertex = [2.25  0.    0.375], x_B = [3, 1]
[[   0.     -67.5      0.    -192.5    -98.25  -146.25 ]
 [   0.       1.25     1.       0.75    -0.025    0.375]
 [   1.      -0.5      0.      -0.5      0.05     2.25 ]]
Delete artificial variables []
x_B = [3, 1]
[[   0.     -67.5      0.    -192.5    -98.25  -146.25 ]
 [   0.       1.25     1.       0.75    -0.025    0.375]
 [   1.      -0.5      0.     

Method 2: Simplex

In [12]:
A = [[1, 2, 2],
     [30, 10, 20.]]

b = [3, 75.]

c = [40, 100, 150.]

basic_var = [0, 1]

tableau = build_tableau(A, b, c)
print(f"x_B = {basic_var}\n{tableau}")

# correcting the coefficients different from zero in the basic var
correct_all_tableau(tableau, basic_var)
# simplex proccess
tableau = simplex(tableau, basic_var)

# Optimal solution for equality constraints
x = np.zeros_like(c)
x[basic_var] = tableau[1:, -1]
print("Optimal solution: x_opt =", x)


x_B = [0, 1]
[[ 40. 100. 150.   0.]
 [  1.   2.   2.   3.]
 [ 30.  10.  20.  75.]]
All tableau corrected
vertex = [2.4], x_B = [1, 2]
[[   0.     0.    54.  -126. ]
 [   1.     0.     0.4    2.4]
 [  -0.     1.     0.8    0.3]]
vertex = [2.25], x_B = [1, 3]
[[   0.     -67.5      0.    -146.25 ]
 [   1.      -0.5      0.       2.25 ]
 [  -0.       1.25     1.       0.375]]
Optimal solution: x_opt = [2.25  0.    0.375]


#### Unbounded model

In [13]:
A = [[1, -1, 1, 0.],
     [-2, 1, 0, 1.]]

b = [1, 2.0]

c = [0, 1, 0, 0.0]

tableau = build_tableau(A, b, c)

basic_var=[2, 3]

simplex(tableau, basic_var);



vertex = [0. 0.], x_B = [3, 4]
[[ 0.  1.  0.  0.  0.]
 [ 1. -1.  1.  0.  1.]
 [-2.  1.  0.  1.  2.]]
vertex = [0. 2.], x_B = [3, 2]
[[ 2.  0.  0. -1. -2.]
 [-1.  0.  1.  1.  3.]
 [-2.  1.  0.  1.  2.]]
The model is unbounded
L = [0. 2. 3. 0.] + λ[-0.  2.  1. -0.]
L = [0. 2.] + λ[-0.  2.]


### CM4E1 Curso: Programación Lineal y flujo en redes, Práctica Dirigida 4

##### 2. Hallar una solución aplicando las tablas del método simplex

a) Simplex method


In [14]:
A = [[2, 1, 1, 0, 0],
     [1, 0, 0, 1, 0],
     [0, 1, 0, 0, 1.]]

b = [9, 4, 3.]

c = [4, 5, 0, 0, 0.]

basic_var = [2, 3, 4]

tableau = build_tableau(A, b, c)
tableau = simplex(tableau, basic_var)
optimal_solution(tableau, basic_var)


vertex = [0. 0.], x_B = [3, 4, 5]
[[4. 5. 0. 0. 0. 0.]
 [2. 1. 1. 0. 0. 9.]
 [1. 0. 0. 1. 0. 4.]
 [0. 1. 0. 0. 1. 3.]]
vertex = [0. 3.], x_B = [3, 4, 2]
[[  4.   0.   0.   0.  -5. -15.]
 [  2.   0.   1.   0.  -1.   6.]
 [  1.   0.   0.   1.   0.   4.]
 [  0.   1.   0.   0.   1.   3.]]
vertex = [3. 3.], x_B = [1, 4, 2]
[[  0.    0.   -2.    0.   -3.  -27. ]
 [  1.    0.    0.5   0.   -0.5   3. ]
 [  0.    0.   -0.5   1.    0.5   1. ]
 [  0.    1.    0.    0.    1.    3. ]]
Optimal solution: x_opt = [3. 3.]


b) Two-phases

In [15]:
# problema b 
A = [[1., 1., 1, 0, 0, 0],
     [-2, -1, 0, 1, 0, 0],
     [0., 1., 0, 0, -1, 1]]

b = [9, 4, 3.]

c = [4, 5, 0, 0.0, 0.0]
c_artificial = [0., 0., 0, 0, 0, -1]

basic_var = [2, 3, 5]
artificial_var = [5]

tableau = build_tableau(A, b, c_artificial)
tableau = two_phases(tableau, c, basic_var, artificial_var)
optimal_solution(tableau, basic_var)


x_B = [3, 4, 6]
[[ 0.  0.  0.  0.  0. -1.  0.]
 [ 1.  1.  1.  0.  0.  0.  9.]
 [-2. -1.  0.  1.  0.  0.  4.]
 [ 0.  1.  0.  0. -1.  1.  3.]]
Cost corrected
x_B = [3, 4, 6]
[[ 0.  1.  0.  0. -1.  0.  3.]
 [ 1.  1.  1.  0.  0.  0.  9.]
 [-2. -1.  0.  1.  0.  0.  4.]
 [ 0.  1.  0.  0. -1.  1.  3.]]
Start phase One
x_B = [3, 4, 2]
[[ 0.  0.  0.  0.  0. -1.  0.]
 [ 1.  0.  1.  0.  1. -1.  6.]
 [-2.  0.  0.  1. -1.  1.  7.]
 [ 0.  1.  0.  0. -1.  1.  3.]]
Delete artificial variables and create a new tableau [5]
Start phase two, put original cost
x_B = [3, 4, 2]
[[ 4.  5.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  6.]
 [-2.  0.  0.  1. -1.  7.]
 [ 0.  1.  0.  0. -1.  3.]]
Cost corrected
vertex = [0. 3.], x_B = [3, 4, 2]
[[  4.   0.   0.   0.   5. -15.]
 [  1.   0.   1.   0.   1.   6.]
 [ -2.   0.   0.   1.  -1.   7.]
 [  0.   1.   0.   0.  -1.   3.]]
vertex = [0. 9.], x_B = [5, 4, 2]
[[ -1.   0.  -5.   0.   0. -45.]
 [  1.   0.   1.   0.   1.   6.]
 [ -1.   0.   1.   1.   0.  13.]
 [  1.   1.   

b) With Big-M method

In [16]:
M = 10

A = [[1., 1., 1, 0, 0, 0],
     [-2, -1, 0, 1, 0, 0],
     [0., 1., 0, 0, -1, 1]]

b = [9, 4, 3.]

c = [4, 5, 0, 0, 0, -M]

basic_var = [2, 3, 5]
artificial_var = [5]

tableau = build_tableau(A, b, c)
tableau = big_M(tableau, basic_var, artificial_var)
optimal_solution(tableau, basic_var)


x_B = [3, 4, 6]
[[  4.   5.   0.   0.   0. -10.   0.]
 [  1.   1.   1.   0.   0.   0.   9.]
 [ -2.  -1.   0.   1.   0.   0.   4.]
 [  0.   1.   0.   0.  -1.   1.   3.]]
Cost corrected
vertex = [0. 0. 9.], x_B = [3, 4, 6]
[[  4.  15.   0.   0. -10.   0.  30.]
 [  1.   1.   1.   0.   0.   0.   9.]
 [ -2.  -1.   0.   1.   0.   0.   4.]
 [  0.   1.   0.   0.  -1.   1.   3.]]
vertex = [0. 3. 6.], x_B = [3, 4, 2]
[[  4.   0.   0.   0.   5. -15. -15.]
 [  1.   0.   1.   0.   1.  -1.   6.]
 [ -2.   0.   0.   1.  -1.   1.   7.]
 [  0.   1.   0.   0.  -1.   1.   3.]]
vertex = [0. 9. 0.], x_B = [5, 4, 2]
[[ -1.   0.  -5.   0.   0. -10. -45.]
 [  1.   0.   1.   0.   1.  -1.   6.]
 [ -1.   0.   1.   1.   0.   0.  13.]
 [  1.   1.   1.   0.   0.   0.   9.]]
Delete artificial variables [5]
x_B = [5, 4, 2]
[[ -1.   0.  -5.   0.   0. -45.]
 [  1.   0.   1.   0.   1.   6.]
 [ -1.   0.   1.   1.   0.  13.]
 [  1.   1.   1.   0.   0.   9.]]
Optimal solution: x_opt = [0. 9.]


##### 6. Resolver por el método de dos faces el siguiente LO

In [17]:
A = [[4., 2, -1, 0, 1, 0],
     [1., 4., 0, -1, 0, 1]]

b = [12, 6.0]

c_artificial = [0., 0., 0, 0, -1, -1]
c = [-2, -3., 0, 0]

basic_var = [4, 5]
artificial_var = [4, 5]

tableau = build_tableau(A, b, c_artificial)
tableau = two_phases(tableau, c, basic_var, artificial_var)
optimal_solution(tableau, basic_var)


x_B = [5, 6]
[[ 0.  0.  0.  0. -1. -1.  0.]
 [ 4.  2. -1.  0.  1.  0. 12.]
 [ 1.  4.  0. -1.  0.  1.  6.]]
Cost corrected
x_B = [5, 6]
[[ 5.  6. -1. -1.  0.  0. 18.]
 [ 4.  2. -1.  0.  1.  0. 12.]
 [ 1.  4.  0. -1.  0.  1.  6.]]
Start phase One
x_B = [5, 2]
[[ 3.5   0.   -1.    0.5   0.   -1.5   9.  ]
 [ 3.5   0.   -1.    0.5   1.   -0.5   9.  ]
 [ 0.25  1.    0.   -0.25  0.    0.25  1.5 ]]
x_B = [1, 2]
[[ 0.          0.          0.          0.         -1.         -1.          0.        ]
 [ 1.          0.         -0.28571429  0.14285714  0.28571429 -0.14285714  2.57142857]
 [ 0.          1.          0.07142857 -0.28571429 -0.07142857  0.28571429  0.85714286]]
Delete artificial variables and create a new tableau [4, 5]
Start phase two, put original cost
x_B = [1, 2]
[[-2.         -3.          0.          0.          0.        ]
 [ 1.          0.         -0.28571429  0.14285714  2.57142857]
 [ 0.          1.          0.07142857 -0.28571429  0.85714286]]
Cost corrected
vertex = [2.571428

In [18]:
A = [[1., 1, 1, 0., 0],
     [-1, 2, 0, -1, 1]]

b = [10, 2.0]

c_artificial = [0., 0., 0, 0, -1]
c = [2, 2., 0, 0]

basic_var = [2, 4]
artificial_var = [4]

tableau = build_tableau(A, b, c_artificial)
tableau = two_phases(tableau, c, basic_var, artificial_var)
optimal_solution(tableau, basic_var)


x_B = [3, 5]
[[ 0.  0.  0.  0. -1.  0.]
 [ 1.  1.  1.  0.  0. 10.]
 [-1.  2.  0. -1.  1.  2.]]
Cost corrected
x_B = [3, 5]
[[-1.  2.  0. -1.  0.  2.]
 [ 1.  1.  1.  0.  0. 10.]
 [-1.  2.  0. -1.  1.  2.]]
Start phase One
x_B = [3, 2]
[[ 0.   0.   0.   0.  -1.   0. ]
 [ 1.5  0.   1.   0.5 -0.5  9. ]
 [-0.5  1.   0.  -0.5  0.5  1. ]]
Delete artificial variables and create a new tableau [4]
Start phase two, put original cost
x_B = [3, 2]
[[ 2.   2.   0.   0.   0. ]
 [ 1.5  0.   1.   0.5  9. ]
 [-0.5  1.   0.  -0.5  1. ]]
Cost corrected
vertex = [0. 1.], x_B = [3, 2]
[[ 3.   0.   0.   1.  -2. ]
 [ 1.5  0.   1.   0.5  9. ]
 [-0.5  1.   0.  -0.5  1. ]]
vertex = [6. 4.], x_B = [1, 2]
[[  0.           0.          -2.           0.         -20.        ]
 [  1.           0.           0.66666667   0.33333333   6.        ]
 [  0.           1.           0.33333333  -0.33333333   4.        ]]
Optimal solution: x_opt = [6. 4.]


##### 7. Aplicar el algoritmo simplex considerando como inicio la solución básica factible asociado al vértice (1, 0) del siguiente LO:

In [19]:
A = [[1, 1, -1, 0, 0, 0, 1],
     [-1, 1, 0, 1, 0, 0, 0],
     [2, 1, 0, 0., 1, 0, 0],
     [1, 0, 0, 0., 0, 1, 0]]

b = [1, 2, 8, 3]

c_artificial = [0, 0, 0, 0, 0, 0, -1.0]
c = [1, 1, 0, 0, 0, 0, 0]

basic_var = [6, 0, 3, 4]
artificial_var = [6]

tableau = build_tableau(A, b, c_artificial)

tableau = two_phases(tableau, c, basic_var, artificial_var)
optimal_solution(tableau, basic_var)


x_B = [7, 1, 4, 5]
[[ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 1.  1. -1.  0.  0.  0.  1.  1.]
 [-1.  1.  0.  1.  0.  0.  0.  2.]
 [ 2.  1.  0.  0.  1.  0.  0.  8.]
 [ 1.  0.  0.  0.  0.  1.  0.  3.]]
Cost corrected
x_B = [7, 1, 4, 5]
[[ 3.  1. -1. -1.  1. -1.  0.  4.]
 [ 1.  1. -1.  0.  0.  0.  1.  1.]
 [-1.  1.  0.  1.  0.  0.  0.  2.]
 [ 2.  1.  0.  0.  1.  0.  0.  8.]
 [ 1.  0.  0.  0.  0.  1.  0.  3.]]
Start phase One
x_B = [1, 1, 4, 5]
[[ 0. -2.  2. -1.  1. -1. -3.  1.]
 [ 1.  1. -1.  0.  0.  0.  1.  1.]
 [ 0.  2. -1.  1.  0.  0.  1.  3.]
 [ 0. -1.  2.  0.  1.  0. -2.  6.]
 [ 0. -1.  1.  0.  0.  1. -1.  2.]]
Delete artificial variables and create a new tableau [6]
Start phase two, put original cost
x_B = [1, 1, 4, 5]
[[ 1.  1.  0.  0.  0.  0.  0.]
 [ 1.  1. -1.  0.  0.  0.  1.]
 [ 0.  2. -1.  1.  0.  0.  3.]
 [ 0. -1.  2.  0.  1.  0.  6.]
 [ 0. -1.  1.  0.  0.  1.  2.]]
Cost corrected
vertex = [3. 0.], x_B = [1, 1, 4, 5]
[[ 0.  0.  1.  0.  0.  0. -1.]
 [ 1.  1. -1.  0.  0.  0.  1.]
 [ 

9. Resolver por el método de dos faces el siguiente LO

In [20]:
A = [[1, 1, 1, 1., 0, 0.],
     [4, 1, 6, 0, -1, 1]]

b = [1, 2.]

c_artificial = [0., 0., 0, 0, 0, -1]
c = [3, 3., 0, 0, 0.0]

basic_var = [2, 4]
artificial_var = [4]

tableau = build_tableau(A, b, c_artificial)
tableau = two_phases(tableau, c, basic_var, artificial_var)
optimal_solution(tableau, basic_var)


x_B = [3, 5]
[[ 0.  0.  0.  0.  0. -1.  0.]
 [ 1.  1.  1.  1.  0.  0.  1.]
 [ 4.  1.  6.  0. -1.  1.  2.]]
Cost corrected
x_B = [3, 5]
[[ 0.  0.  0.  0.  0. -1.  0.]
 [ 1.  1.  1.  1.  0.  0.  1.]
 [ 4.  1.  6.  0. -1.  1.  2.]]
Start phase One
x_B = [3, 1]
[[ 0.    0.    0.    0.    0.   -1.    0.  ]
 [ 0.    0.75 -0.5   1.    0.25 -0.25  0.5 ]
 [ 1.    0.25  1.5   0.   -0.25  0.25  0.5 ]]
Delete artificial variables and create a new tableau [4]
Start phase two, put original cost
x_B = [3, 1]
[[ 3.    3.    0.    0.    0.    0.  ]
 [ 0.    0.75 -0.5   1.   -0.25  0.5 ]
 [ 1.    0.25  1.5   0.    0.25  0.5 ]]
Cost corrected
vertex = [0.5 0.  0.5], x_B = [3, 1]
[[ 0.    2.25 -4.5   0.   -0.75 -1.5 ]
 [ 0.    0.75 -0.5   1.   -0.25  0.5 ]
 [ 1.    0.25  1.5   0.    0.25  0.5 ]]
vertex = [0.33333333 0.66666667 0.        ], x_B = [2, 1]
[[ 0.          0.         -3.         -3.          0.         -3.        ]
 [ 0.          1.         -0.66666667  1.33333333 -0.33333333  0.66666667]
 [ 1.

### CM4E1 Curso: Práctica Calificada 3

##### 3. Determinar el valor óptimo (si existe solución) del siguiente LO

\begin{align*}
-\max \quad  -x_1& - 2x_2& +3x_3& - 3x_4& \\
\text { s.t. } \quad  3x_1& +2x_2& - x_3& + x_4& + x_5& {}   {}& {} {}& &= 1\\
                      x_1& - 3x_2& + 2x_3& -2x_4& {} {}& - {x_6}& + x_7& &=6 \\
                      x_1&\ge0,&x_2 \ge0,&x_3 \ge0,&x_4 \ge0,& x_5\ge0,&x_6 \ge0,& x_7\ge0&
\end{align*}

In [21]:
A = [[3, 2., -1, 1, 1, 0., 0],
     [1, -3, 2, -2, 0, -1, 1]]
b = [1, 6.]

c = [-1, -2, 3, -3, 0., 0, 0]
c_artificial = [0, 0, 0, 0, 0, 0, -1]

tableau = build_tableau(A, b, c_artificial)

basic_var = [4, 6]
artificial_var = [6]
tableau = two_phases(tableau, c, basic_var, artificial_var)

x_B = [5, 7]
[[ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 3.  2. -1.  1.  1.  0.  0.  1.]
 [ 1. -3.  2. -2.  0. -1.  1.  6.]]
Cost corrected
x_B = [5, 7]
[[ 1. -3.  2. -2.  0. -1.  0.  6.]
 [ 3.  2. -1.  1.  1.  0.  0.  1.]
 [ 1. -3.  2. -2.  0. -1.  1.  6.]]
Start phase One
x_B = [5, 3]
[[ 0.   0.   0.   0.   0.   0.  -1.   0. ]
 [ 3.5  0.5  0.   0.   1.  -0.5  0.5  4. ]
 [ 0.5 -1.5  1.  -1.   0.  -0.5  0.5  3. ]]
Delete artificial variables and create a new tableau [6]
Start phase two, put original cost
x_B = [5, 3]
[[-1.  -2.   3.  -3.   0.   0.   0. ]
 [ 3.5  0.5  0.   0.   1.  -0.5  4. ]
 [ 0.5 -1.5  1.  -1.   0.  -0.5  3. ]]
Cost corrected
vertex = [0. 0. 3. 0.], x_B = [5, 3]
[[-2.5  2.5  0.   0.   0.   1.5 -9. ]
 [ 3.5  0.5  0.   0.   1.  -0.5  4. ]
 [ 0.5 -1.5  1.  -1.   0.  -0.5  3. ]]
vertex = [ 0.  8. 15.  0.], x_B = [2, 3]
[[-20.   0.   0.   0.  -5.   4. -29.]
 [  7.   1.   0.   0.   2.  -1.   8.]
 [ 11.   0.   1.  -1.   3.  -2.  15.]]
The model is unbounded
L = [ 0.  8. 15.  0.  

##### 4.	Elaborar un algoritmo que al ingresar una tabla simplex (cuya información es representada en una matriz y un vector que indica cuales son las variables básicas asociadas), indique si es correcto la tabla y obtenga el LO original asociado.

In [31]:
tableau = sp.Matrix([[3, 2, 0, 0, 0, 0, 0],
                     [1, 1, 1, 0, 0, 0, 9],
                     [3, 1, 0, 1, 0, 0, 18],
                     [1, 0, 0, 0, 1, 0, 7],
                     [0, 1, 0, 0, 0, 1, 6]])

basic_var = [2, 3, 4, 5]
check_tableau(tableau, basic_var)


Si es una tabla simplex, cuyo LO original asociado es


True

In [29]:
tableau = sp.Matrix([[0, 0, -3/2, -1/2, 0, 0, -45/2],
                     [0, 1,  3/2,  1/2, 0, 0, 9/2],
                     [1, 0, -1/2,  1/2, 0, 0, 9/2],
                     [0, 0,  1/2, -1/2, 1, 0, 5/2],
                     [0, 0, -3/2,  1/2, 0, 1, 3/2]])

basic_var = [1, 0, 4, 5]
check_tableau(tableau, basic_var, True)


Si es una tabla simplex, cuyo LO original asociado es


True

In [30]:
A = [[-1, 1, 1, 3, 1, 0],
     [1, -1, 2, 1, 0, 1.]]

b = [1, 1.]

c = [2, 4, 10, 15., 0, 0]

basic_var = [4, 5]

tableau = build_tableau(A, b, c)
simplex(tableau, basic_var);


vertex = [0. 0. 0. 0.], x_B = [5, 6]
[[ 2.  4. 10. 15.  0.  0.  0.]
 [-1.  1.  1.  3.  1.  0.  1.]
 [ 1. -1.  2.  1.  0.  1.  1.]]
vertex = [0.         0.         0.         0.33333333], x_B = [4, 6]
[[ 7.         -1.          5.          0.         -5.          0.         -5.        ]
 [-0.33333333  0.33333333  0.33333333  1.          0.33333333  0.          0.33333333]
 [ 1.33333333 -1.33333333  1.66666667  0.         -0.33333333  1.          0.66666667]]
vertex = [0.5 0.  0.  0.5], x_B = [4, 1]
[[ 0.    6.   -3.75  0.   -3.25 -5.25 -8.5 ]
 [ 0.    0.    0.75  1.    0.25  0.25  0.5 ]
 [ 1.   -1.    1.25  0.   -0.25  0.75  0.5 ]]
The model is unbounded
L = [0.5 0.  0.  0.5 0.  0. ] + λ[ 1. -0. -0. -0. -0. -0.]
L = [0.5 0.  0.  0.5] + λ[ 1. -0. -0. -0.]
