## Examen Parcial

In [5]:
import sys
sys.path.insert(0, "..")

from algorithms.simplex_algorithms import *
from algorithms.basic_solution import basic_solutions
import numpy as np
import sympy as sp

np.set_printoptions(suppress=True, linewidth=np.nan)


#### Pregunta 1

\begin{align*}
\max -2x_1 + x_2 + x_3\\
s.t. -x_1 + x_2 + x_3 \le 2\\
            x_1 - x_2 + x_3 \le 2\\
            x_1, x_2 \ge 0, x_3 \text{ free}
\end{align*}

In [6]:
A = sp.Matrix([[-1, 1, 1, -1, 1, 0],
               [1, -1, 1, -1, 0, 1]])

b = sp.Matrix([2, 2])

basic_solutions(A, b)

Number of combinations: 15
Basic solution 1
Matrix det == 0; not invertible.


Basic solution 2


Basic solution 3


Basic solution 4


Basic solution 5


Basic solution 6


Basic solution 7


Basic solution 8


Basic solution 9


Basic solution 10
Matrix det == 0; not invertible.


Basic solution 11


Basic solution 12


Basic solution 13


Basic solution 14


Basic solution 15


#### Pregunta 3

\begin{align*}
\max 3x_1 - 3x_2 + x_3\\
s.t.    x_1 + 3x_2 - 2x_3 \ge 5\\
        -3x_1 - 2x_2 + x_3 \le 4\\
        x_1, x_2, x_3 \ge 0
\end{align*}

In [7]:
A = [[1, 3, -2., -1, 0, 1],
     [-3, -2, 1, 0., 1, 0]]

b = [5, 4.]

c = [3, -3, 1, 0, 0.]

c_artificial = [0, 0, 0, 0, 0, -1.]

basic_var = [5, 4]

artificial_var = [5]

tableau = build_tableau(A, b, c_artificial)
two_phases(tableau, c, basic_var, artificial_var);


x_B = [6, 5]
[[ 0.  0.  0.  0.  0. -1.  0.]
 [ 1.  3. -2. -1.  0.  1.  5.]
 [-3. -2.  1.  0.  1.  0.  4.]]
Cost corrected
x_B = [6, 5]
[[ 1.  3. -2. -1.  0.  0.  5.]
 [ 1.  3. -2. -1.  0.  1.  5.]
 [-3. -2.  1.  0.  1.  0.  4.]]
Start phase One
x_B = [2, 5]
[[ 0.          0.          0.          0.          0.         -1.          0.        ]
 [ 0.33333333  1.         -0.66666667 -0.33333333  0.          0.33333333  1.66666667]
 [-2.33333333  0.         -0.33333333 -0.66666667  1.          0.66666667  7.33333333]]
Delete artificial variables and create a new tableau [5]
Start phase two, put original cost
x_B = [2, 5]
[[ 3.         -3.          1.          0.          0.          0.        ]
 [ 0.33333333  1.         -0.66666667 -0.33333333  0.          1.66666667]
 [-2.33333333  0.         -0.33333333 -0.66666667  1.          7.33333333]]
Cost corrected
vertex = [0.         1.66666667 0.         0.         7.33333333], x_B = [2, 5]
[[ 4.          0.         -1.         -1.          0. 